# Generated by Django 4.1.5 on 2023-01-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0003_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
