# Generated by Django 4.1.5 on 2023-01-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0004_alter_todo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='com',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complited', models.CharField(max_length=100)),
            ],
        ),
    ]
